#name: '이슈 생성'
#description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
#labels: [ feat ]
#title: '이슈 이름을 작성해주세요'
#body:
##  - type: input
##    id: parentKey
##    attributes:
##      label: '🎟️ 상위 작업 (Ticket Number)'
##      description: '상위 작업의 Ticket Number를 기입해주세요'
##      placeholder: 'PRJ-00'
##    validations:
##      required: true
#
#  - type: input
#    id: branch
#    attributes:
#      label: '🌳 브랜치명 (Branch)'
#      description: '영어로 브랜치명을 작성해주세요'
#    validations:
#      required: true
#
#  - type: input
#    id: description
#    attributes:
#      label: '📝 상세 내용(Description)'
#      description: '이슈에 대해서 간략히 설명해주세요'
#      value: '지라를 연동한다'
#
#
#  - type: textarea
#    id: tasks
#    attributes:
#      label: '✅ 체크리스트(Tasks)'
#      description: '해당 이슈에 대해 필요한 작업목록을 작성해주세요'
#      value: |
#        - [ ] Task1
#        - [ ] Task2
#    validations:
#      required: true
#
#    #https://lamerry.tistory.com/entry/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%EC%84%9C-Jira-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0-3-Github-Actions%EB%A1%9C-GithubJira-%EC%9D%B4%EC%8A%88-%EC%9E%90%EB%8F%99%ED%99%94
#    #https://velog.io/@dsa2341/github-action%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%EC%9E%90%EB%8F%99%EC%9C%BC%EB%A1%9C-Jira-Ticket-%EC%9D%B4%EB%8F%99%ED%95%98%EA%B8%B0
