name: review and sent Discord message

on:
  pull_request_review:
    types: [ submitted ]  # 리뷰가 제출될 때
  pull_request_review_comment:
    types: [ created ]  # 리뷰 코멘트가 생성될 때


jobs:
  send_discord_message:
    runs-on: ubuntu-latest
    steps:
      - name: 작업자와 리뷰어를 결정한다.
        run: |
          if [ "${{ github.actor }}" == "david-parkk" ]; then
              echo "DISCORD_OWNER_ID=<@568069533214965760>" >> $GITHUB_ENV
              echo "DISCORD_REVIEWER_ID=<@373383545873235970>" >> $GITHUB_ENV
          else
              echo "DISCORD_OWNER_ID=<@373383545873235970>" >> $GITHUB_ENV
              echo "DISCORD_REVIEWER_ID=<@568069533214965760>" >> $GITHUB_ENV
          fi
      - name: 리뷰 요청 Discord 메세지를 보낸다
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: 개발진스
          DISCORD_AVATAR: "https://github.com/user-attachments/assets/1ff8e3ad-40c1-4a99-85cf-367376ed5d93"
          DISCORD_EMBEDS: '
          [
            { 
              "url": "${{github.event.pull_request.html_url}}",
              "title": ":musical_note: 리뷰 코멘트가 생성되었습니다. 확인해주세요",
  
              "fields": [
                
                {
                  "name": "리뷰어",
                  "value": "${{env.DISCORD_REVIEWER_ID}}\n",
                  "inline": true
                },
                {
                  "name": " ",
                  "value": "${{env.DISCORD_OWNER_ID}}\n\u200B\n\u200B\n",
                  "inline": true
                },
                {
                  "name": "내용",
                  "value": "[${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})"
  
                }
              ] 
            }
          ]'



      - name: 리뷰와 코멘트 처리
        run: |
          echo "리뷰가 제출되었습니다!"
          echo "리뷰의 상태는: ${{ github.event.review.state }}"
          echo "리뷰어: ${{ github.event.review.user.login }}"
          echo "리뷰 코멘트 내용: ${{ github.event.comment.body }}"