name: test

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - opened
      - reopened
      - synchronize

permissions:
  actions: write  # 워크플로우 트리거 권한 설정

#동시성 환경을 해결한다
concurrency:

  group: ${{ github.ref }} # 동일한 PR에 대한 식별자
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo 'The triggering workflow passed'