name: test

on:
  pull_request:
    branches:
      - 'develop'
    types:
      - opened
      - reopened
      - synchronize

permissions:
  actions: write  # 워크플로우 트리거 권한 설정



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo 'The triggering workflow passed'